### ISSUE TITLE
Incorrect value for MArkdown use

### ISSUE THREAD

**Issue by dspinellis** [panos1b/Vathmologia_Ergasion#1]
The `README USES MARKDOWN` field is incorrectly `0` for the repo https://github.com/ElenaSkep/Dream-Team.

**Comment by panos1b** [comment]
For grading README markdown usage, the raw text is compared with the markdown text. This is done by multiplying the readme markdown factor (found on line 72 in [`constants.py`](https://github.com/panos1b/Vathmologia_Ergasion/blob/master/constants.py#:~:text=FACTOR_README_MARKDOWN)) with the length of characters of the raw readme (text only). 

The factor is set by default to 1,08. This means that for every 100 characters there should be 8 markdown elements. This factor was chosen after going through a sample of repositories both from our projects and generally on GitHub.

Between those trialed were:
<html xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:w="urn:schemas-microsoft-com:office:word"
xmlns:m="http://schemas.microsoft.com/office/2004/12/omml"
xmlns="http://www.w3.org/TR/REC-html40">

<head>

<meta name=ProgId content=Word.Document>
<meta name=Generator content="Microsoft Word 15">
<meta name=Originator content="Microsoft Word 15">
<link rel=File-List
href="file:///C:/Users/PANOSD~1/AppData/Local/Temp/msohtmlclip1/01/clip_filelist.xml">
<link rel=Preview
href="file:///C:/Users/PANOSD~1/AppData/Local/Temp/msohtmlclip1/01/clip_preview.wmf">

<link rel=themeData
href="file:///C:/Users/PANOSD~1/AppData/Local/Temp/msohtmlclip1/01/clip_themedata.thmx">
<link rel=colorSchemeMapping
href="file:///C:/Users/PANOSD~1/AppData/Local/Temp/msohtmlclip1/01/clip_colorschememapping.xml">


</head>

<body lang=EN-US style='tab-interval:36.0pt;word-wrap:break-word'>




Repository | Factor
-- | --
AnnaMariaDimareli/Java2 | 1,13
StefanKourou/ProgrammingII | 1,48
anastasiaant000/social-media-app | 1,11
spinellis/alexandria3k | 1,18




</body>

</html>

The factor 1,08 seemed low enough to avoid any false-positives.

The repository [ElenaSkep/Dream-Team](https://github.com/ElenaSkep/Dream-Team) had a raw character length of 2650 and a markdown character length of 2765 (i.e., only 15 markdown elements used) well below the 1,08 threshold and therefore was considered as not using enough markdown compared to raw text.

Of course, the program can be (re)-run with a threshold of 1, where even a single markdown element will set the grade as 1.

Please close this issue accordingly

**Comment by dspinellis** [comment]
Addressed with 4a76f1b57b6eaa1ca2f75646f5f97d991c55353a.
